# Imports

In [ ]:
from cobra.io import read_sbml_model
import micom

# Test

In [ ]:
m1 = read_sbml_model("/home/arog/models/xml/ic_1306.xml")
m2 = read_sbml_model("/home/arog/models/xml/iCN900.xml")

,id,genus,species,reactions,metabolites,sample_id,abundance
0,Escherichia_coli_1,Escherichia,Escherichia coli 0,95,72,sample_1,366
1,Escherichia_coli_2,Escherichia,Escherichia coli 1,95,72,sample_1,84
2,Escherichia_coli_3,Escherichia,Escherichia coli 2,95,72,sample_1,844
3,Escherichia_coli_4,Escherichia,Escherichia coli 3,95,72,sample_1,928
0,Escherichia_coli_1,Escherichia,Escherichia coli 0,95,72,sample_2,282
1,Escherichia_coli_2,Escherichia,Escherichia coli 1,95,72,sample_2,127
2,Escherichia_coli_3,Escherichia,Escherichia coli 2,95,72,sample_2,47
3,Escherichia_coli_4,Escherichia,Escherichia coli 3,95,72,sample_2,809
0,Escherichia_coli_1,Escherichia,Escherichia coli 0,95,72,sample_3,969
1,Escherichia_coli_2,Escherichia,Escherichia coli 1,95,72,sample_3,836
2,Escherichia_coli_3,Escherichia,Escherichia coli 2,95,72,sample_3,628
3,Escherichia_coli_4,Escherichia,Escherichia coli 3,95,72,sample_3,145
0,Escherichia_coli_1,Escherichia,Escherichia coli 0,95,72,sample_4,370
1,Escherichia_coli_2,Escherichia,Escherichia coli 1,95,72,sample_4,551
2,Escherichia_coli_3,Escherichia,Escherichia coli 2,95,72,sample_4,128
3,Escherichia_coli_4,Escherichia,Escherichia coli 3,95,72,sample_4,45